#!/usr/bin/env python3
"""aysinc generator"""


import asyncio
import random


async_generator = __import__('0-async_generator').async_generator

async def async_comprehension():
    """
    Coroutine that collects 10 random numbers from the async_generator using async comprehension.

    This function uses an asynchronous list comprehension to collect the first 10 random numbers 
    generated by the async_generator coroutine. It stops collecting once 10 numbers are gathered.

    Returns:
        list: A list containing 10 random numbers generated asynchronously.
    """
    result = [num async fir num in async_generator() in len(result) < 10]
    return result
